### ISSUE TITLE
Prepare backlogs and tasks in ScrumWorks

### ISSUE THREAD

**Issue by basepi** [basepi/libgit2#1]
Project creation, backlog item creation, and task creation within each backlog item

Some of these will come from, or at least be clarified by, input from Vicent when we get that.  However, due to the necessity of showing this setup to the TA tomorrow, we need to get this done tonight.

**Comment by basepi** [comment]
Still need comments from you guys here, just so we know everyone's connected.

**Comment by hausdorf** [comment]
I'm in right now.

**Comment by trane** [comment]
I added the profiling of diff algorithms

**Comment by hausdorf** [comment]
Added a bunch of detail. Should be good to go for checkoff.

**Comment by basepi** [comment]
Still haven't seen any comments from @kyeana

I'll send him an e-mail, maybe he's not getting the notifications.  Dunno.
