### ISSUE TITLE
Scrumworks Sprint 2 update

### ISSUE THREAD

**Issue by basepi** [basepi/libgit2#10]
Everyone please go into scrumworks and take a look.  I figure once we actually start sprint 2, I'll move the unfinished tasks over to it from Sprint 1.  Doesn't allow me to add pieces of backlog items, requires whole backlock item, so I just added all of the main merge implementation to sprint 2, even though I doubt we'll get it done. When you look at how things have worked out, this is really only a 3 week project, not 5.  (Since we have all the beginning and end administrative stuff)  We're doing the final presentation 2 weeks from tomorrow.  Crazy stuff.

**Comment by trane** [comment]
Awesome.
