### ISSUE TITLE
Core protocol team's commits break the build

### ISSUE THREAD

**Issue by hausdorf** [basepi/libgit2#12]
Merge introduced in [833e409f527993bb8726](https://github.com/crakdmirror/libgit2/commit/833e409f527993bb87261bc6a39a0fe09efc1a16) breaks build. If you need help building, [take a look at this](https://github.com/crakdmirror/libgit2/wiki/Building%2C-testing%2C-and-using-libgit2).

**Comment by basepi** [comment]
This is why, to my knowledge, we haven't pushed any of our code to development, but have kept it in interface.......

**Comment by basepi** [comment]
Oh, @trane just mentioned he merged them together.

**Comment by trane** [comment]
It also looks like Landon fixed it about 2 hours ago. Not sure if you are commenting on the latest commit.

**Comment by vimalloc** [comment]
Just pushed up a new commit that fixes all compile issues.

There are still a few compile warnings that I need to fix and that would break if you tried to run them right now, but that shouldn't stop you from being able to compile anything.

I will continue working on this throughout the day.

**Comment by basepi** [comment]
I'll be working on this this evening as well.

**Comment by hausdorf** [comment]
Sorry, @crakdmirror or @kyeana, can you merge one more time and push up to your branch? That's just usually the way it works -- the person who wrote the code gets to merge it into the other branch. It would be the same if Andrew and I wrote code and merged it into `development`.

**Comment by basepi** [comment]
Are you saying you reverted or something?  I thought it was already merged?

**Comment by hausdorf** [comment]
I did revert it, sorry. I wasn't sure if it would be fixed immediately or not, so I just did what I had to do to make it testable.

**Comment by basepi** [comment]
You wanna take this, @kyeana, since you already know how to make it work
again?

**Comment by vimalloc** [comment]
Sure thing. Are you wanting me to pull development or dev-diff-algo?

**Comment by vimalloc** [comment]
and damn the comment and close button being there...

**Comment by hausdorf** [comment]
Typically what you'd do is to pull `dev-diff-algo` and just merge it in. Then push it up to `development-interface`. Then we pull from you.

**Comment by basepi** [comment]
I know, right?  I find it easiest to just reply to the notification e-mail.
 You'll have to ask Alex, I'm still not up to date on what exactly was/needs
to be merged.

**Comment by basepi** [comment]
Do we know if the libgit2 repo frowns upon merge commits as opposed to
rebasing?  I was reading about rebasing over the weekend, and I've found a
few OSS projects which, under their "guidelines for contributing" don't like
merge commits.  Just wondered if it might be an issue later, and if we
should be rebasing rather than merging?

**Comment by vimalloc** [comment]
dev-diff-algo is missing at least the function git_repository_workdir() in repository.h, which I need for some of the stuff in diff.c.

Could it be that function was created in the development branch, and that branch wasn't merged with dev-diff-algo?

**Comment by hausdorf** [comment]
Almost certainly no, but to confirm, I pulled `development` and merged. Looking at the [revert commit](https://github.com/crakdmirror/libgit2/commit/0c162a81ffb9fbf21e1c824801c140db360044e9), it seems that I reverted that change.

**Comment by vimalloc** [comment]
Can you push that change up to github? I don't see it there right now.

**Comment by hausdorf** [comment]
You don't see the revert commit I linked to?

**Comment by hausdorf** [comment]
Also @crakdmirror, should not be a problem, though I'll check with Vicent.

**Comment by vimalloc** [comment]
I see the revert commit, but that removed functionality needed for diff.c. Specifically, include/git2/repository.h line 213 of that revert. 

Without the development branch merged back in my code wont compile.

**Comment by hausdorf** [comment]
I am technically merged with development. If you run the merge command you will get a helpful message telling you you're up-to-date. Besides, if it's true that repository.c is missing stuff, then probably a lot of other places are too.

You could, if you want, revert the revert, I suppose.

**Comment by vimalloc** [comment]
Ok. Do you want me to do that on your branch? I don't want to break any code you have done, since I have just been doing stuff on my branch...

**Comment by hausdorf** [comment]
It should, strictly speaking, be done on your branch. I'll look at the diffs.

**Comment by vimalloc** [comment]
Uh, maybe I am missing something here, but that revert that reverted too much was done on your branch, so wouldn't it make more sense for you to fix it so that I don't unknowingly break something you have done?

**Comment by hausdorf** [comment]
Well, first, reverting that commit will quite literally just undo whatever I reverted. You don't have to make choices. It just works. Second, it is reverting work that _you_ did -- I didn't revert our stuff. So reverting would not break our stuff. And third, strictly speaking no, because you're doing it to merge your stuff in, so if it breaks something, it points to you as the committer who did it.

**Comment by hausdorf** [comment]
So, what would happen ideally is, you'd pull, and then revert our commit, and then fix everything that was broken, and then push up to your branch and then we'd pull that.

**Comment by vimalloc** [comment]
Done. 

Everything compile normally, with the only warnings being unused parameters.

**Comment by hausdorf** [comment]
Awesome, thanks. _kisses Landon_
