### ISSUE TITLE
We free a pointer that wasn't malloc'd

### ISSUE THREAD

**Issue by hausdorf** [basepi/libgit2#15]
PROBLEM: A call to `git_diff_no_index()` will allocate the contents of file at params `filepath1` and `filepath2` to a `char *buffer1` and `char *buffer2`. Running this method will produce the following error:
`
a.out(5679) malloc: *** error for object 0x100800000: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
[1]    5679 abort      ./a.out
`
What's going on here is that we're free'ing [here](https://github.com/crakdmirror/libgit2/blob/dc37da2b202a928a782d30756cd93a0fc327ca88/src/diff.c#L65) without actually having malloc'd the memory to begin with.

NOTES:

I would've just fixed this, but I wasn't sure if that would conflict with resolution of [#14](https://github.com/crakdmirror/libgit2/issues/14).

**Comment by vimalloc** [comment]
It should be getting malloc'd through load file, hence why we pass it a double pointer.

I can take a look at it in a bit.

**Comment by hausdorf** [comment]
@kyeana, take your time. Filed a bug report so that we could get around to it when we want to.

You can see what the bug looks like for us [here](https://github.com/crakdmirror/libgit2/blob/e7b6795377c29fdf68366d0b36b9657fe64d4c6f/src/diff.c#L91)

**Comment by vimalloc** [comment]
Awesome sauce

**Comment by hausdorf** [comment]
What's really happening here is that the call to `load_file()` in [this line](https://github.com/crakdmirror/libgit2/blob/dev-diff-algo/src/diff.c#L67) fails at some point. Since it never gets malloc'd, freeing it causes an error.

**Comment by vimalloc** [comment]
Problem was char *buffer1; initializes buffer1 to garbage, not to null, thus the if(buffer1) returns true and we try to free stuff we never malloc'd. 

Fix in my branch.

**Comment by basepi** [comment]
Did you push that to the server, @kyeana?  The comments in, for example, in git_diff_no_index, there are still comments referencing #15, and yes, I've pulled from master very recently.

**Comment by basepi** [comment]
OK, I found your fix, you just didn't remove the comments.
