### ISSUE TITLE
Use or define the libdiff malloc

### ISSUE THREAD

**Issue by hausdorf** [basepi/libgit2#23]
We're currently just calling `free()` and `malloc()`. This isn't extensible. We should define some sort of macro that specifies which malloc we're using, and it should probably default to libgit's malloc. I propose we call it `ld_malloc()`

**Comment by trane** [comment]
I have been coding against...
ld_malloc()
and
ld_free()
for patience.

**Comment by hausdorf** [comment]
I have misinformed you. libgit uses this style: `git__malloc()`, with two underscores. Correspondingly, I've just incorporated a libdiff malloc under the name `ld__malloc` in `libdiff.h`. You can see this implementation [here](https://github.com/crakdmirror/libgit2/commit/bef2f375cd2a4ba2bc4d0864a0d3eba20fed133f#L0R44).

Apologies for the confusion.

**Comment by trane** [comment]
cool.

**Comment by hausdorf** [comment]
Shouldn't have been closed; we need to actually implement it now.

**Comment by hausdorf** [comment]
This is now implemented for libdiff.

@kyeana, @crakdmirror, what malloc are you using? Can I close this?

**Comment by vimalloc** [comment]
Git__malloc
On Apr 22, 2011 10:08 PM, "DrSleep" <
reply@reply.github.com>
wrote:

**Comment by hausdorf** [comment]
Awesome. Then I'm closing this issue.
