### ISSUE TITLE
We need to rehearse the final presentation and what-not.

### ISSUE THREAD

**Issue by basepi** [basepi/libgit2#25]
Just need to decide what all we need to do to prepare for this.  I suppose we can just give each person stuff to talk about decide ordering, and wing it.  I'm not too worried about the public speaking part of it, once we have all the content.

This is obviously low-priority until we have the actual code done, but thought I'd throw up an issue.

EDIT:  So when are we going to do it?  I suppose we'll talk more at the meeting on Saturday.

**Comment by hausdorf** [comment]
YES.

**Comment by hausdorf** [comment]
We should call our presentation "Learn you a git (for great
good!)http://learnyousomeerlang.com/
"

**Comment by trane** [comment]
We are meeting on Monday @ 8:45pm in the CADE for great good.
