### ISSUE TITLE
Function Declarations

### ISSUE THREAD

**Issue by vimalloc** [basepi/libgit2#26]
We are declaring some function at the top of .c files like such: https://github.com/crakdmirror/libgit2/blob/development/src/diff.c#L13

I understand why we would do this, but glancing around it doesn't look like the rest of the project is doing this. Is it ok if we remove these to keep the same feel as the rest of the project?

**Comment by hausdorf** [comment]
Probably right. I'm going to worry less about style issues right now, but in the future it will be important.

**Comment by basepi** [comment]
Sounds fine to me.  Theoretically, load_file, which was on the line you
referenced, won't be even necessary, and ya, I figure we should follow the
style of the project.
