### ISSUE TITLE
use c89 style comments

### ISSUE THREAD

**Issue by trane** [basepi/libgit2#33]
According to the wiki:

Linux style for comments is the C89 "/\* ... */" style. Don't use C99-style "// ..." comments.

Are we following the same? If so, we need to change a bunch of stuff.

**Comment by vimalloc** [comment]
I have been doing it that way.

On Fri, 22 Apr 2011 13:51:51 -0600, trane  
reply@reply.github.com  
wrote:

> According to the wiki:
> 
> Linux style for comments is the C89 "/\* ... */" style. Don't use  
> C99-style "// ..." comments.
> 
> Are we following the same? If so, we need to change a bunch of stuff.

## 

Using Opera's revolutionary e-mail client: http://www.opera.com/mail/

**Comment by hausdorf** [comment]
Style issues should be covered in [#22](https://github.com/crakdmirror/libgit2/issues/22).

**Comment by basepi** [comment]
I have been.
