### ISSUE TITLE
git diff with newly added files.

### ISSUE THREAD

**Issue by vimalloc** [basepi/libgit2#35]
In git, if you use git diff and there is a newly added file in your file system but not in the repository, then the contents of that file are not part of the diff. If you delete a file from the file system that was in the repository, then that file is still included in the diff.

Should we follow this behavior? If so it would make the git_diff() function virtually done, minus actually doing the diffs on the files that have changed.

**Comment by hausdorf** [comment]
Nice catch, man. I vote that we should remain consistent with git's functionality.
