### ISSUE TITLE
C doesn't allow function overloading, and this is annoying

### ISSUE THREAD

**Issue by hausdorf** [basepi/libgit2#6]
I think you got this, @crakdmirror.

**Comment by basepi** [comment]
Trying to figure out what you want me to do with this....  =\

**Comment by hausdorf** [comment]
Don't be obtuse, I expect you to fix it. You should probably start by proposing a change to the [C spec](http://eli-project.sourceforge.net/c_html/c.html), and then you should probably [submit a patch to the GCC](http://gcc.gnu.org/). I need you do complete this by Wednesday if possible, and Friday at the very latest.

**Comment by vimalloc** [comment]
heheheh

**Comment by vimalloc** [comment]
And i accidentally closed this. What was i thinking...

**Comment by basepi** [comment]
I'm going to need some leverage.  Anyone have time to go plant a few bombs for me?
